//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources.Resources.Boards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BoardResources_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoardResources_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Resources.Boards.BoardResources.pl", typeof(BoardResources_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź AI była pusta lub null..
        /// </summary>
        public static string AiResponseEmptyOrNull {
            get {
                return ResourceManager.GetString("AiResponseEmptyOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono pliku w magazynie blob..
        /// </summary>
        public static string BlobFileNotFound {
            get {
                return ResourceManager.GetString("BlobFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko właściciel może usunąć tablicę..
        /// </summary>
        public static string BoardDeleteNotOwner {
            get {
                return ResourceManager.GetString("BoardDeleteNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator tablicy nie może być pustym GUID-em..
        /// </summary>
        public static string BoardIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("BoardIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak lub nieprawidłowy identyfikator tablicy w ścieżce żądania..
        /// </summary>
        public static string BoardIdNotInRoute {
            get {
                return ResourceManager.GetString("BoardIdNotInRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator tablicy jest wymagany..
        /// </summary>
        public static string BoardIdRequired {
            get {
                return ResourceManager.GetString("BoardIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator listy tablicy nie może być pustym GUID-em..
        /// </summary>
        public static string BoardListIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("BoardListIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator listy tablicy jest wymagany..
        /// </summary>
        public static string BoardListIdRequired {
            get {
                return ResourceManager.GetString("BoardListIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablica nie znaleziona..
        /// </summary>
        public static string BoardNotFound {
            get {
                return ResourceManager.GetString("BoardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć ostatniego uprawnienia członka..
        /// </summary>
        public static string CannotRemoveLastPermission {
            get {
                return ResourceManager.GetString("CannotRemoveLastPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można usunąć właściciela tablicy..
        /// </summary>
        public static string CannotRemoveOwner {
            get {
                return ResourceManager.GetString("CannotRemoveOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz usuwać uprawnień samemu sobie..
        /// </summary>
        public static string CannotRemoveOwnPermissions {
            get {
                return ResourceManager.GetString("CannotRemoveOwnPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie możesz usunąć siebie z tablicy..
        /// </summary>
        public static string CannotRemoveSelf {
            get {
                return ResourceManager.GetString("CannotRemoveSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator karty nie może być pustym GUID-em..
        /// </summary>
        public static string CardIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("CardIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator karty jest wymagany..
        /// </summary>
        public static string CardIdRequired {
            get {
                return ResourceManager.GetString("CardIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karta nie znaleziona..
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakończenia nie może być w przyszłości..
        /// </summary>
        public static string CompletedAtCannotBeInFuture {
            get {
                return ResourceManager.GetString("CompletedAtCannotBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis nie może przekraczać {0} znaków..
        /// </summary>
        public static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis nie może składać się wyłącznie ze znaków odstępu..
        /// </summary>
        public static string DescriptionNotWhitespace {
            get {
                return ResourceManager.GetString("DescriptionNotWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis jest wymagany..
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis nie może przekraczać 500 znaków..
        /// </summary>
        public static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail jest nieprawidłowy..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się pobrać pliku z magazynu blob..
        /// </summary>
        public static string FailedToDownloadBlob {
            get {
                return ResourceManager.GetString("FailedToDownloadBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się przesłać pliku do magazynu blob..
        /// </summary>
        public static string FailedToUploadBlob {
            get {
                return ResourceManager.GetString("FailedToUploadBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar pliku nie może przekraczać {0} MB..
        /// </summary>
        public static string FileMaxSize {
            get {
                return ResourceManager.GetString("FileMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik nie może być pusty..
        /// </summary>
        public static string FileNotEmpty {
            get {
                return ResourceManager.GetString("FileNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik jest wymagany..
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieobsługiwany typ pliku. Dozwolone typy: JPEG, PNG, GIF..
        /// </summary>
        public static string FileTypeInvalid {
            get {
                return ResourceManager.GetString("FileTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa wartość ARGB koloru..
        /// </summary>
        public static string InvalidColorArgbValue {
            get {
                return ResourceManager.GetString("InvalidColorArgbValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowa struktura JSON z AI: {0}.
        /// </summary>
        public static string InvalidJsonStructureFromAi {
            get {
                return ResourceManager.GetString("InvalidJsonStructureFromAi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator listy nie może być pusty..
        /// </summary>
        public static string ListIdRequired {
            get {
                return ResourceManager.GetString("ListIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista nie znaleziona..
        /// </summary>
        public static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono pliku..
        /// </summary>
        public static string MediaNotFound {
            get {
                return ResourceManager.GetString("MediaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Członek nie posiada określonego uprawnienia..
        /// </summary>
        public static string MemberDoesNotHavePermission {
            get {
                return ResourceManager.GetString("MemberDoesNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator członka jest wymagany..
        /// </summary>
        public static string MemberIdRequired {
            get {
                return ResourceManager.GetString("MemberIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Członek nie znaleziony..
        /// </summary>
        public static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany członek nie należy do tablicy..
        /// </summary>
        public static string MemberNotFoundOnBoard {
            get {
                return ResourceManager.GetString("MemberNotFoundOnBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje wymaganego uprawnienia do wykonania tej akcji..
        /// </summary>
        public static string MissingRequiredPermission {
            get {
                return ResourceManager.GetString("MissingRequiredPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie dodano żadnych nowych uprawnień..
        /// </summary>
        public static string NoNewPermissionsAdded {
            get {
                return ResourceManager.GetString("NoNewPermissionsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostałeś zaproszony do tablicy.
        /// </summary>
        public static string NotificationBoardInviteTitle {
            get {
                return ResourceManager.GetString("NotificationBoardInviteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostałeś usunięty z tablicy.
        /// </summary>
        public static string NotificationBoardRemovedTitle {
            get {
                return ResourceManager.GetString("NotificationBoardRemovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jesteś członkiem tej tablicy..
        /// </summary>
        public static string NotMemberOfBoard {
            get {
                return ResourceManager.GetString("NotMemberOfBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak obrazu tła do usunięcia..
        /// </summary>
        public static string NoWallpaperToDelete {
            get {
                return ResourceManager.GetString("NoWallpaperToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Żądanie do API Ollama nie powiodło się. Kod statusu: {0}.
        /// </summary>
        public static string OllamaApiRequestFailedWithStatusCode {
            get {
                return ResourceManager.GetString("OllamaApiRequestFailedWithStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź API Ollama nie zawiera pola &apos;response&apos;..
        /// </summary>
        public static string OllamaApiResponseMissingResponseField {
            get {
                return ResourceManager.GetString("OllamaApiResponseMissingResponseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas przetwarzania żądania do API Ollama..
        /// </summary>
        public static string OllamaApiUnexpectedError {
            get {
                return ResourceManager.GetString("OllamaApiUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko członkowie tablicy mogą usunąć obraz tła..
        /// </summary>
        public static string OnlyMembersCanDeleteWallpaper {
            get {
                return ResourceManager.GetString("OnlyMembersCanDeleteWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko członkowie tablicy mogą ustawić obraz tła..
        /// </summary>
        public static string OnlyMembersCanSetWallpaper {
            get {
                return ResourceManager.GetString("OnlyMembersCanSetWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko właściciel tablicy może dodawać uprawnienia członkom..
        /// </summary>
        public static string OnlyOwnerCanAddPermissions {
            get {
                return ResourceManager.GetString("OnlyOwnerCanAddPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tylko właściciel tablicy może usuwać uprawnienia członkom..
        /// </summary>
        public static string OnlyOwnerCanRemovePermissions {
            get {
                return ResourceManager.GetString("OnlyOwnerCanRemovePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściciel nie może opuścić tablicy. Usuń ją zamiast tego..
        /// </summary>
        public static string OwnerCannotLeaveBoard {
            get {
                return ResourceManager.GetString("OwnerCannotLeaveBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator właściciela nie może być pustym GUID-em..
        /// </summary>
        public static string OwnerIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("OwnerIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator właściciela jest wymagany..
        /// </summary>
        public static string OwnerIdRequired {
            get {
                return ResourceManager.GetString("OwnerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o podanym identyfikatorze właściciela nie istnieje..
        /// </summary>
        public static string OwnerIdUserNotExist {
            get {
                return ResourceManager.GetString("OwnerIdUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uprawnienie jest wymagane..
        /// </summary>
        public static string PermissionRequired {
            get {
                return ResourceManager.GetString("PermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozycja nie może być pusta..
        /// </summary>
        public static string PositionCannotBeNull {
            get {
                return ResourceManager.GetString("PositionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozycja musi być większa od zera..
        /// </summary>
        public static string PositionGreaterThanZero {
            get {
                return ResourceManager.GetString("PositionGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozycja musi być nieujemna..
        /// </summary>
        public static string PositionMustBeNonNegative {
            get {
                return ResourceManager.GetString("PositionMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator żądającego użytkownika nie może być pustym GUID-em..
        /// </summary>
        public static string RequestingUserIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("RequestingUserIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator żądającego użytkownika jest wymagany..
        /// </summary>
        public static string RequestingUserIdRequired {
            get {
                return ResourceManager.GetString("RequestingUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o podanym identyfikatorze żądającego nie istnieje..
        /// </summary>
        public static string RequestingUserIdUserNotExist {
            get {
                return ResourceManager.GetString("RequestingUserIdUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypisz rolę członkowi..
        /// </summary>
        public static string RoleIdRequired {
            get {
                return ResourceManager.GetString("RoleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł nie może być pusty..
        /// </summary>
        public static string TitleCannotBeNull {
            get {
                return ResourceManager.GetString("TitleCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł jest nieprawidłowy..
        /// </summary>
        public static string TitleInvalid {
            get {
                return ResourceManager.GetString("TitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł nie może przekraczać {0} znaków..
        /// </summary>
        public static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł jest wymagany..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas pobierania pliku z magazynu blob..
        /// </summary>
        public static string UnexpectedBlobDownloadError {
            get {
                return ResourceManager.GetString("UnexpectedBlobDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator użytkownika jest nieprawidłowy..
        /// </summary>
        public static string UserIdInvalid {
            get {
                return ResourceManager.GetString("UserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator użytkownika nie może być pustym GUID-em..
        /// </summary>
        public static string UserIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("UserIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator użytkownika nie może być pusty..
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik do dodania nie istnieje..
        /// </summary>
        public static string UserIdToAddUserNotExist {
            get {
                return ResourceManager.GetString("UserIdToAddUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik jest już członkiem tej tablicy..
        /// </summary>
        public static string UserIsMemberAlready {
            get {
                return ResourceManager.GetString("UserIsMemberAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika jest nieprawidłowa..
        /// </summary>
        public static string UsernameInvalid {
            get {
                return ResourceManager.GetString("UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można pobrać uprawnień użytkownika..
        /// </summary>
        public static string UserPermissionsNotFound {
            get {
                return ResourceManager.GetString("UserPermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widoczność nie może być pusta..
        /// </summary>
        public static string VisibilityCannotBeNull {
            get {
                return ResourceManager.GetString("VisibilityCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy poziom widoczności..
        /// </summary>
        public static string VisibilityInvalid {
            get {
                return ResourceManager.GetString("VisibilityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widoczność nie może być pusta..
        /// </summary>
        public static string VisibilityRequired {
            get {
                return ResourceManager.GetString("VisibilityRequired", resourceCulture);
            }
        }
    }
}
