//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources.Resources.Boards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BoardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoardResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Resources.Boards.BoardResources", typeof(BoardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found in blob storage..
        /// </summary>
        public static string BlobFileNotFound {
            get {
                return ResourceManager.GetString("BlobFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the owner can delete the board..
        /// </summary>
        public static string BoardDeleteNotOwner {
            get {
                return ResourceManager.GetString("BoardDeleteNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board ID cannot be an empty GUID..
        /// </summary>
        public static string BoardIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("BoardIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board ID is missing or invalid in route..
        /// </summary>
        public static string BoardIdNotInRoute {
            get {
                return ResourceManager.GetString("BoardIdNotInRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board ID is required..
        /// </summary>
        public static string BoardIdRequired {
            get {
                return ResourceManager.GetString("BoardIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board List ID cannot be an empty GUID..
        /// </summary>
        public static string BoardListIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("BoardListIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board List ID is required..
        /// </summary>
        public static string BoardListIdRequired {
            get {
                return ResourceManager.GetString("BoardListIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board not found..
        /// </summary>
        public static string BoardNotFound {
            get {
                return ResourceManager.GetString("BoardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the last permission from a member..
        /// </summary>
        public static string CannotRemoveLastPermission {
            get {
                return ResourceManager.GetString("CannotRemoveLastPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the owner of the board..
        /// </summary>
        public static string CannotRemoveOwner {
            get {
                return ResourceManager.GetString("CannotRemoveOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove permissions from yourself..
        /// </summary>
        public static string CannotRemoveOwnPermissions {
            get {
                return ResourceManager.GetString("CannotRemoveOwnPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove yourself from the board..
        /// </summary>
        public static string CannotRemoveSelf {
            get {
                return ResourceManager.GetString("CannotRemoveSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID cannot be an empty GUID..
        /// </summary>
        public static string CardIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("CardIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card ID is required..
        /// </summary>
        public static string CardIdRequired {
            get {
                return ResourceManager.GetString("CardIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not found..
        /// </summary>
        public static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletedAt cannot be in the future..
        /// </summary>
        public static string CompletedAtCannotBeInFuture {
            get {
                return ResourceManager.GetString("CompletedAtCannotBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed {0} characters..
        /// </summary>
        public static string DescriptionMaxLength {
            get {
                return ResourceManager.GetString("DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 500 characters..
        /// </summary>
        public static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download file from blob storage..
        /// </summary>
        public static string FailedToDownloadBlob {
            get {
                return ResourceManager.GetString("FailedToDownloadBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file to blob storage..
        /// </summary>
        public static string FailedToUploadBlob {
            get {
                return ResourceManager.GetString("FailedToUploadBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size cannot exceed {0} MB..
        /// </summary>
        public static string FileMaxSize {
            get {
                return ResourceManager.GetString("FileMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be empty..
        /// </summary>
        public static string FileNotEmpty {
            get {
                return ResourceManager.GetString("FileNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required..
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file type. Allowed types are: JPEG, PNG, GIF..
        /// </summary>
        public static string FileTypeInvalid {
            get {
                return ResourceManager.GetString("FileTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color ARGB value..
        /// </summary>
        public static string InvalidColorArgbValue {
            get {
                return ResourceManager.GetString("InvalidColorArgbValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List ID cannot be empty..
        /// </summary>
        public static string ListIdRequired {
            get {
                return ResourceManager.GetString("ListIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List not found..
        /// </summary>
        public static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media not found.
        /// </summary>
        public static string MediaNotFound {
            get {
                return ResourceManager.GetString("MediaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member does not have the specified permission..
        /// </summary>
        public static string MemberDoesNotHavePermission {
            get {
                return ResourceManager.GetString("MemberDoesNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID is required..
        /// </summary>
        public static string MemberIdRequired {
            get {
                return ResourceManager.GetString("MemberIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found..
        /// </summary>
        public static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified member does not belong to the board..
        /// </summary>
        public static string MemberNotFoundOnBoard {
            get {
                return ResourceManager.GetString("MemberNotFoundOnBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lack the required permission for this action..
        /// </summary>
        public static string MissingRequiredPermission {
            get {
                return ResourceManager.GetString("MissingRequiredPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new permissions were added..
        /// </summary>
        public static string NoNewPermissionsAdded {
            get {
                return ResourceManager.GetString("NoNewPermissionsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to a board.
        /// </summary>
        public static string NotificationBoardInviteTitle {
            get {
                return ResourceManager.GetString("NotificationBoardInviteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been removed from the board.
        /// </summary>
        public static string NotificationBoardRemovedTitle {
            get {
                return ResourceManager.GetString("NotificationBoardRemovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a member of this board..
        /// </summary>
        public static string NotMemberOfBoard {
            get {
                return ResourceManager.GetString("NotMemberOfBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wallpaper image to delete..
        /// </summary>
        public static string NoWallpaperToDelete {
            get {
                return ResourceManager.GetString("NoWallpaperToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only board members can delete the wallpaper image..
        /// </summary>
        public static string OnlyMembersCanDeleteWallpaper {
            get {
                return ResourceManager.GetString("OnlyMembersCanDeleteWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only board members can set the wallpaper image..
        /// </summary>
        public static string OnlyMembersCanSetWallpaper {
            get {
                return ResourceManager.GetString("OnlyMembersCanSetWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the board owner can add permissions to members..
        /// </summary>
        public static string OnlyOwnerCanAddPermissions {
            get {
                return ResourceManager.GetString("OnlyOwnerCanAddPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the board owner can remove permissions from members..
        /// </summary>
        public static string OnlyOwnerCanRemovePermissions {
            get {
                return ResourceManager.GetString("OnlyOwnerCanRemovePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner cannot leave the board. Delete it instead..
        /// </summary>
        public static string OwnerCannotLeaveBoard {
            get {
                return ResourceManager.GetString("OwnerCannotLeaveBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID cannot be an empty GUID..
        /// </summary>
        public static string OwnerIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("OwnerIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner ID is required..
        /// </summary>
        public static string OwnerIdRequired {
            get {
                return ResourceManager.GetString("OwnerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the specified Owner ID does not exist..
        /// </summary>
        public static string OwnerIdUserNotExist {
            get {
                return ResourceManager.GetString("OwnerIdUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is required..
        /// </summary>
        public static string PermissionRequired {
            get {
                return ResourceManager.GetString("PermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position cannot be null..
        /// </summary>
        public static string PositionCannotBeNull {
            get {
                return ResourceManager.GetString("PositionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position must be greater than zero..
        /// </summary>
        public static string PositionGreaterThanZero {
            get {
                return ResourceManager.GetString("PositionGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position must be a non-negative..
        /// </summary>
        public static string PositionMustBeNonNegative {
            get {
                return ResourceManager.GetString("PositionMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting User ID cannot be an empty GUID..
        /// </summary>
        public static string RequestingUserIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("RequestingUserIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting User ID is required..
        /// </summary>
        public static string RequestingUserIdRequired {
            get {
                return ResourceManager.GetString("RequestingUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the given Requesting User ID does not exist..
        /// </summary>
        public static string RequestingUserIdUserNotExist {
            get {
                return ResourceManager.GetString("RequestingUserIdUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a role to the member..
        /// </summary>
        public static string RoleIdRequired {
            get {
                return ResourceManager.GetString("RoleIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be null..
        /// </summary>
        public static string TitleCannotBeNull {
            get {
                return ResourceManager.GetString("TitleCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is invalid..
        /// </summary>
        public static string TitleInvalid {
            get {
                return ResourceManager.GetString("TitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot exceed {0} characters..
        /// </summary>
        public static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while downloading the file from blob storage..
        /// </summary>
        public static string UnexpectedBlobDownloadError {
            get {
                return ResourceManager.GetString("UnexpectedBlobDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is invalid..
        /// </summary>
        public static string UserIdInvalid {
            get {
                return ResourceManager.GetString("UserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID cannot be an empty GUID..
        /// </summary>
        public static string UserIdNotEmptyGuid {
            get {
                return ResourceManager.GetString("UserIdNotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID cannot be empty..
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User to add does not exist..
        /// </summary>
        public static string UserIdToAddUserNotExist {
            get {
                return ResourceManager.GetString("UserIdToAddUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already a member of this board..
        /// </summary>
        public static string UserIsMemberAlready {
            get {
                return ResourceManager.GetString("UserIsMemberAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is invalid..
        /// </summary>
        public static string UsernameInvalid {
            get {
                return ResourceManager.GetString("UsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve user permissions..
        /// </summary>
        public static string UserPermissionsNotFound {
            get {
                return ResourceManager.GetString("UserPermissionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility cannot be null..
        /// </summary>
        public static string VisibilityCannotBeNull {
            get {
                return ResourceManager.GetString("VisibilityCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid visibility level..
        /// </summary>
        public static string VisibilityInvalid {
            get {
                return ResourceManager.GetString("VisibilityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility cannot be null..
        /// </summary>
        public static string VisibilityRequired {
            get {
                return ResourceManager.GetString("VisibilityRequired", resourceCulture);
            }
        }
    }
}
